"$schema" = 'https://starship.rs/config-schema.json'
#
# Based on the `apple` theme from oh-my-zsh
# See: https://github.com/ohmyzsh/ohmyzsh/blob/master/themes/apple.zsh-theme
#

format = "[→](purple)$git_branch$git_status $directory$character"
add_newline = false

[username]
disabled = true

[hostname]
disabled = true

[directory]
format = '[$path/](cyan)'
truncate_to_repo = true

[git_branch]
format = ' [$branch](green)'
symbol = ''

[git_status]
format = '$staged$modified'
staged = '[+](yellow)'
modified = '[*](red)'

[character]
success_symbol = ''
error_symbol = '[!](red)'
